#--------gateway------------
server:
  port: 6657

spring:
  application:
    name: gateway
  cloud:
    nacos:
      config:
        group: my_cloud
        server-addr: 127.0.0.1:8848
    loadbalancer:
      nacos:
        enabled: true
      ribbon:
        enabled: false
  config:
    import: nacos:gateway.yml?refresh=true
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      connect-timeout: 3000ms
      lettuce:
        pool:
          max-active: 20 #最大连接数，负值表示没有限制，默认为8
          max-wait: -1   #最大阻塞等待时间，负值表示没有限制，默认-1
          max-idle: 8    #最大空闲连接数，默认8
          min-idle: 0    #最小空闲连接数，默认0
custom:
  security:
    ignore-uri-list: /oauth/**,/resource/**, /webjars/**, /login, /error, /oauth2/consent/parameters, /favicon.ico
    login-url: http://lineben.com/login
    consent-page-uri: http://lineben.com/consent
    device-activate-uri: http://lineben.com/activate
    device-activated-uri: http://lineben.com/activated
    issuer-url: http://192.168.31.221:8081

