#--------webflux------------
server:
  port: 6659
  servlet:
    session:
      cookie:
        domain: lineben.com
      timeout: 24h
spring:
  application:
    name: webflux-resource
  main:
    web-application-type: reactive
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  config:
    import: nacos:webflux.yml?refresh=true

  datasource: #配置数据源
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: woaini1398
    url: jdbc:sqlserver://localhost:1433;databaseName=reactProject

mybatis:
  type-aliases-package: com.chen.pojo
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.chen.pojo
  mapper-locations: classpath:mapper/*.xml