server:
  port: 8081

spring:
  application:
    name: auth-server
  cloud:
    nacos:
      config:
        group: my_cloud
        server-addr: 127.0.0.1:8848
  config:
    import: nacos:auth.yml?refresh=true
  jpa:
    database: sql_server
    open-in-view: true

  datasource: #SQL Server 数据源
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: woaini1398
    url: jdbc:sqlserver://localhost:1433;databaseName=reactProject;encrypt=false;
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      connect-timeout: 3000ms
      lettuce:
        pool:
          max-active: 20 #最大连接数，负值表示没有限制，默认为8
          max-wait: -1   #最大阻塞等待时间，负值表示没有限制，默认-1
          max-idle: 8    #最大空闲连接数，默认8
          min-idle: 0    #最小空闲连接数，默认0

custom:
  security:
    ignore-uri-list: assets/**, /webjars/**, /login,/logout, /getCaptcha, /getSmsCaptcha, /error, /oauth2/consent/parameters, /favicon.ico, /qrCode/login/**
    login-url: http://lineben.com/login
    consent-page-uri: http://lineben.com/consent
    device-activate-uri: http://lineben.com/activate
    device-activated-uri: http://lineben.com/activated
    issuer-url: http://192.168.31.221:8081


mybatis:
  type-aliases-package: com.chen.pojo
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.chen.pojo
  mapper-locations: classpath:mapper/*.xml